import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { CASE_GROUPS, allCases } from '../../scripts/parity/case-groups.js';
import { CLOCK_CASES } from '../../scripts/parity/clock-cases.js';
import { EXPORT_DIR, buildExport, strayFiles } from '../../scripts/parity/export.js';
import { REPO_ROOT } from '../../scripts/parity/server-command.js';

// The cargo test rust/tests/parity.rs (#371) reads the parity cases and their golden results from
// rust/tests/data/parity/, because cargo-mutants runs `cargo test` in a copy of rust/ alone and can't reach
// scripts/parity (ADR-0033). The files are generated by scripts/export-parity.ts from the case files and the golden files
// (scripts/parity/expected, the tool contract). These guards keep them in step, so a case edited or re-recorded
// without exporting again fails here, and so the Rust test can never hold the server to something the Node cases
// no longer say.

describe('the parity export for the cargo test', () => {
  const files = buildExport();

  it('is what scripts/export-parity.ts writes', () => {
    for (const [name, content] of files) {
      const full = join(EXPORT_DIR, name);
      expect(existsSync(full), `rust/tests/data/parity/${name} is missing; run npx vite-node scripts/export-parity.ts`).toBe(true);
      expect(readFileSync(full, 'utf8') === content, `rust/tests/data/parity/${name} is out of date; run npx vite-node scripts/export-parity.ts`).toBe(true);
    }
  });

  it('has no file the export does not write', () => {
    expect(strayFiles(files)).toEqual([]);
  });

  it('holds every case of every group, each with the golden result recorded for it', () => {
    for (const group of CASE_GROUPS) {
      const exported = JSON.parse(files.get(`${group.name}.json`)!) as { group: string; cases: Array<{ name: string; expected: unknown }> };
      expect(exported.group).toBe(group.name);
      expect(exported.cases.map(c => c.name)).toEqual(group.cases.map(c => c.name));
      const golden = JSON.parse(readFileSync(join(REPO_ROOT, 'scripts', 'parity', 'expected', `${group.name}.json`), 'utf8')) as Record<string, unknown>;
      for (const c of exported.cases) expect(c.expected, c.name).toEqual(golden[c.name]);
    }
    expect(files.size).toBe(CASE_GROUPS.length + 2);
    expect(allCases().length).toBeGreaterThan(900);
  });

  it('lists the cases that read today as the Node harness does, and the recorded tool list unchanged', () => {
    expect(JSON.parse(files.get('clock-cases.json')!)).toEqual(CLOCK_CASES);
    expect(files.get('tool-list.json')).toBe(readFileSync(join(REPO_ROOT, 'scripts', 'parity', 'expected', 'tool-list.json'), 'utf8'));
  });
});
